package com.dgrissom.deobfuscatednms;

// a way of accessing sounds from SoundRegistry

//todo finish
// class nj
public class SoundRegistry {
    public static final Sound a;
    public static final Sound b;
    public static final Sound c;
    public static final Sound d;
    public static final Sound e;
    public static final Sound f;
    public static final Sound g;
    public static final Sound h;
    public static final Sound i;
    public static final Sound j;
    public static final Sound k;
    public static final Sound l;
    public static final Sound m;
    public static final Sound n;
    public static final Sound o;
    public static final Sound p;
    public static final Sound q;
    public static final Sound r;
    public static final Sound s;
    public static final Sound t;
    public static final Sound u;
    public static final Sound v;
    public static final Sound w;
    public static final Sound x;
    public static final Sound y;
    public static final Sound z;
    public static final Sound A;
    public static final Sound B;
    public static final Sound C;
    public static final Sound D;
    public static final Sound E;
    public static final Sound F;
    public static final Sound G;
    public static final Sound H;
    public static final Sound I;
    public static final Sound J;
    public static final Sound K;
    public static final Sound L;
    public static final Sound M;
    public static final Sound N;
    public static final Sound O;
    public static final Sound P;
    public static final Sound Q;
    public static final Sound R;
    public static final Sound S;
    public static final Sound T;
    public static final Sound U;
    public static final Sound V;
    public static final Sound W;
    public static final Sound X;
    public static final Sound Y;
    public static final Sound Z;
    public static final Sound aa;
    public static final Sound ab;
    public static final Sound ac;
    public static final Sound ad;
    public static final Sound ae;
    public static final Sound af;
    public static final Sound ag;
    public static final Sound ah;
    public static final Sound ai;
    public static final Sound aj;
    public static final Sound ak;
    public static final Sound al;
    public static final Sound am;
    public static final Sound an;
    public static final Sound ao;
    public static final Sound ap;
    public static final Sound aq;
    public static final Sound ar;
    public static final Sound as;
    public static final Sound at;
    public static final Sound au;
    public static final Sound av;
    public static final Sound aw;
    public static final Sound ax;
    public static final Sound ay;
    public static final Sound az;
    public static final Sound aA;
    public static final Sound aB;
    public static final Sound aC;
    public static final Sound aD;
    public static final Sound aE;
    public static final Sound aF;
    public static final Sound aG;
    public static final Sound aH;
    public static final Sound aI;
    public static final Sound aJ;
    public static final Sound aK;
    public static final Sound aL;
    public static final Sound aM;
    public static final Sound aN;
    public static final Sound aO;
    public static final Sound aP;
    public static final Sound aQ;
    public static final Sound aR;
    public static final Sound aS;
    public static final Sound aT;
    public static final Sound aU;
    public static final Sound aV;
    public static final Sound aW;
    public static final Sound aX;
    public static final Sound aY;
    public static final Sound aZ;
    public static final Sound ba;
    public static final Sound bb;
    public static final Sound bc;
    public static final Sound bd;
    public static final Sound be;
    public static final Sound bf;
    public static final Sound bg;
    public static final Sound bh;
    public static final Sound bi;
    public static final Sound bj;
    public static final Sound bk;
    public static final Sound bl;
    public static final Sound bm;
    public static final Sound bn;
    public static final Sound bo;
    public static final Sound bp;
    public static final Sound bq;
    public static final Sound br;
    public static final Sound bs;
    public static final Sound bt;
    public static final Sound bu;
    public static final Sound bv;
    public static final Sound bw;
    public static final Sound bx;
    public static final Sound by;
    public static final Sound bz;
    public static final Sound bA;
    public static final Sound bB;
    public static final Sound bC;
    public static final Sound bD;
    public static final Sound bE;
    public static final Sound bF;
    public static final Sound bG;
    public static final Sound bH;
    public static final Sound bI;
    public static final Sound bJ;
    public static final Sound bK;
    public static final Sound bL;
    public static final Sound bM;
    public static final Sound bN;
    public static final Sound bO;
    public static final Sound bP;
    public static final Sound bQ;
    public static final Sound bR;
    public static final Sound bS;
    public static final Sound bT;
    public static final Sound bU;
    public static final Sound bV;
    public static final Sound bW;
    public static final Sound bX;
    public static final Sound bY;
    public static final Sound bZ;
    public static final Sound ca;
    public static final Sound cb;
    public static final Sound cc;
    public static final Sound cd;
    public static final Sound ce;
    public static final Sound cf;
    public static final Sound cg;
    public static final Sound ch;
    public static final Sound ci;
    public static final Sound cj;
    public static final Sound ck;
    public static final Sound cl;
    public static final Sound cm;
    public static final Sound cn;
    public static final Sound co;
    public static final Sound cp;
    public static final Sound cq;
    public static final Sound cr;
    public static final Sound cs;
    public static final Sound ct;
    public static final Sound cu;
    public static final Sound cv;
    public static final Sound cw;
    public static final Sound cx;
    public static final Sound cy;
    public static final Sound cz;
    public static final Sound cA;
    public static final Sound cB;
    public static final Sound cC;
    public static final Sound cD;
    public static final Sound cE;
    public static final Sound cF;
    public static final Sound cG;
    public static final Sound cH;
    public static final Sound cI;
    public static final Sound cJ;
    public static final Sound cK;
    public static final Sound cL;
    public static final Sound cM;
    public static final Sound cN;
    public static final Sound cO;
    public static final Sound cP;
    public static final Sound cQ;
    public static final Sound cR;
    public static final Sound cS;
    public static final Sound cT;
    public static final Sound cU;
    public static final Sound cV;
    public static final Sound cW;
    public static final Sound cX;
    public static final Sound cY;
    public static final Sound cZ;
    public static final Sound da;
    public static final Sound db;
    public static final Sound dc;
    public static final Sound dd;
    public static final Sound de;
    public static final Sound df;
    public static final Sound dg;
    public static final Sound dh;
    public static final Sound di;
    public static final Sound dj;
    public static final Sound dk;
    public static final Sound dl;
    public static final Sound dm;
    public static final Sound dn;
    public static final Sound do;
    public static final Sound dp;
    public static final Sound dq;
    public static final Sound dr;
    public static final Sound ds;
    public static final Sound dt;
    public static final Sound du;
    public static final Sound dv;
    public static final Sound dw;
    public static final Sound dx;
    public static final Sound dy;
    public static final Sound dz;
    public static final Sound dA;
    public static final Sound dB;
    public static final Sound dC;
    public static final Sound dD;
    public static final Sound dE;
    public static final Sound dF;
    public static final Sound dG;
    public static final Sound dH;
    public static final Sound dI;
    public static final Sound dJ;
    public static final Sound dK;
    public static final Sound dL;
    public static final Sound dM;
    public static final Sound dN;
    public static final Sound dO;
    public static final Sound dP;
    public static final Sound dQ;
    public static final Sound dR;
    public static final Sound dS;
    public static final Sound dT;
    public static final Sound dU;
    public static final Sound dV;
    public static final Sound dW;
    public static final Sound dX;
    public static final Sound dY;
    public static final Sound dZ;
    public static final Sound ea;
    public static final Sound eb;
    public static final Sound ec;
    public static final Sound ed;
    public static final Sound ee;
    public static final Sound ef;
    public static final Sound eg;
    public static final Sound eh;
    public static final Sound ei;
    public static final Sound ej;
    public static final Sound ek;
    public static final Sound el;
    public static final Sound em;
    public static final Sound en;
    public static final Sound eo;
    public static final Sound ep;
    public static final Sound eq;
    public static final Sound er;
    public static final Sound es;
    public static final Sound et;
    public static final Sound eu;
    public static final Sound ev;
    public static final Sound ew;
    public static final Sound ex;
    public static final Sound ey;
    public static final Sound ez;
    public static final Sound eA;
    public static final Sound eB;
    public static final Sound eC;
    public static final Sound eD;
    public static final Sound eE;
    public static final Sound eF;
    public static final Sound eG;
    public static final Sound eH;
    public static final Sound eI;
    public static final Sound eJ;
    public static final Sound eK;
    public static final Sound eL;
    public static final Sound eM;
    public static final Sound eN;
    public static final Sound eO;
    public static final Sound eP;
    public static final Sound eQ;
    public static final Sound eR;
    public static final Sound eS;
    public static final Sound eT;
    public static final Sound eU;
    public static final Sound eV;
    public static final Sound eW;
    public static final Sound eX;
    public static final Sound eY;
    public static final Sound eZ;
    public static final Sound fa;
    public static final Sound fb;
    public static final Sound fc;
    public static final Sound fd;
    public static final Sound fe;
    public static final Sound ff;
    public static final Sound fg;
    public static final Sound fh;
    public static final Sound fi;
    public static final Sound fj;
    public static final Sound fk;
    public static final Sound fl;
    public static final Sound fm;
    public static final Sound fn;
    public static final Sound fo;
    public static final Sound fp;
    public static final Sound fq;
    public static final Sound fr;
    public static final Sound fs;
    public static final Sound ft;
    public static final Sound fu;
    public static final Sound fv;
    public static final Sound fw;
    public static final Sound fx;
    public static final Sound fy;
    public static final Sound fz;
    public static final Sound fA;
    public static final Sound fB;
    public static final Sound fC;
    public static final Sound fD;
    public static final Sound fE;
    public static final Sound fF;
    public static final Sound fG;
    public static final Sound fH;
    public static final Sound fI;
    public static final Sound fJ;
    public static final Sound fK;
    public static final Sound fL;
    public static final Sound fM;
    public static final Sound fN;
    public static final Sound fO;
    public static final Sound fP;
    public static final Sound fQ;
    public static final Sound fR;
    public static final Sound fS;
    public static final Sound fT;
    public static final Sound fU;
    public static final Sound fV;
    public static final Sound fW;
    public static final Sound fX;
    public static final Sound fY;
    public static final Sound fZ;
    public static final Sound ga;
    public static final Sound gb;
    public static final Sound gc;
    public static final Sound gd;
    public static final Sound ge;
    public static final Sound gf;
    public static final Sound gg;
    public static final Sound gh;
    public static final Sound gi;
    public static final Sound gj;
    public static final Sound gk;
    public static final Sound gl;
    public static final Sound gm;
    public static final Sound gn;
    public static final Sound go;
    public static final Sound gp;
    public static final Sound gq;
    public static final Sound gr;
    public static final Sound gs;
    public static final Sound gt;
    public static final Sound gu;
    public static final Sound gv;
    public static final Sound gw;
    public static final Sound gx;
    public static final Sound gy;
    public static final Sound gz;
    public static final Sound gA;
    public static final Sound gB;
    public static final Sound gC;
    public static final Sound gD;
    public static final Sound gE;
    public static final Sound gF;
    public static final Sound gG;
    public static final Sound gH;
    public static final Sound gI;
    public static final Sound gJ;
    public static final Sound gK;
    public static final Sound gL;
    public static final Sound gM;
    public static final Sound gN;
    public static final Sound gO;
    public static final Sound gP;
    public static final Sound gQ;
    public static final Sound gR;
    public static final Sound gS;
    public static final Sound gT;
    public static final Sound gU;
    public static final Sound gV;
    public static final Sound gW;
    public static final Sound gX;
    public static final Sound gY;
    public static final Sound gZ;
    public static final Sound ha;
    public static final Sound hb;
    public static final Sound hc;
    public static final Sound hd;
    public static final Sound he;
    public static final Sound hf;
    public static final Sound hg;
    public static final Sound hh;
    public static final Sound hi;
    public static final Sound hj;
    public static final Sound hk;
    public static final Sound hl;
    public static final Sound hm;
    public static final Sound hn;
    public static final Sound ho;
    public static final Sound hp;
    public static final Sound hq;
    public static final Sound hr;
    public static final Sound hs;
    public static final Sound ht;
    public static final Sound hu;
    public static final Sound hv;
    public static final Sound hw;
    public static final Sound hx;
    public static final Sound hy;
    public static final Sound hz;
    public static final Sound hA;
    public static final Sound hB;
    public static final Sound hC;
    public static final Sound hD;
    public static final Sound hE;
    public static final Sound hF;
    public static final Sound hG;
    public static final Sound hH;
    public static final Sound hI;
    public static final Sound hJ;
    public static final Sound hK;
    public static final Sound hL;
    public static final Sound hM;
    public static final Sound hN;
    public static final Sound hO;
    public static final Sound hP;
    public static final Sound hQ;
    public static final Sound hR;
    public static final Sound hS;
    public static final Sound hT;
    public static final Sound hU;

    private static Sound requestSound(String name) {
        // .a is the da<kn, ni> property
        Sound ☃1 = (Sound) Sound.a.c(new kn(name));
        if (☃1 == null) {
            throw new IllegalStateException("Invalid Sound requested: " + name);
        } else {
            return ☃1;
        }
    }

    static {
        if (!kq.a()) {
            throw new RuntimeException("Accessed Sounds before Bootstrap!");
        } else {
            a = requestSound("ambient.cave");
            b = requestSound("block.anvil.break");
            c = requestSound("block.anvil.destroy");
            d = requestSound("block.anvil.fall");
            e = requestSound("block.anvil.hit");
            f = requestSound("block.anvil.land");
            g = requestSound("block.anvil.place");
            h = requestSound("block.anvil.step");
            i = requestSound("block.anvil.use");
            j = requestSound("entity.armorstand.break");
            k = requestSound("entity.armorstand.fall");
            l = requestSound("entity.armorstand.hit");
            m = requestSound("entity.armorstand.place");
            n = requestSound("item.armor.equip_chain");
            o = requestSound("item.armor.equip_diamond");
            p = requestSound("item.armor.equip_generic");
            q = requestSound("item.armor.equip_gold");
            r = requestSound("item.armor.equip_iron");
            s = requestSound("item.armor.equip_leather");
            t = requestSound("entity.arrow.hit");
            u = requestSound("entity.arrow.hit_player");
            v = requestSound("entity.arrow.shoot");
            w = requestSound("entity.bat.ambient");
            x = requestSound("entity.bat.death");
            y = requestSound("entity.bat.hurt");
            z = requestSound("entity.bat.loop");
            A = requestSound("entity.bat.takeoff");
            B = requestSound("entity.blaze.ambient");
            C = requestSound("entity.blaze.burn");
            D = requestSound("entity.blaze.death");
            E = requestSound("entity.blaze.hurt");
            F = requestSound("entity.blaze.shoot");
            G = requestSound("entity.bobber.splash");
            H = requestSound("entity.bobber.throw");
            I = requestSound("item.bottle.fill");
            J = requestSound("item.bottle.fill_dragonbreath");
            K = requestSound("block.brewing_stand.brew");
            L = requestSound("item.bucket.empty");
            M = requestSound("item.bucket.empty_lava");
            N = requestSound("item.bucket.fill");
            O = requestSound("item.bucket.fill_lava");
            P = requestSound("entity.cat.ambient");
            Q = requestSound("entity.cat.death");
            R = requestSound("entity.cat.hiss");
            S = requestSound("entity.cat.hurt");
            T = requestSound("entity.cat.purr");
            U = requestSound("entity.cat.purreow");
            V = requestSound("block.chest.close");
            W = requestSound("block.chest.locked");
            X = requestSound("block.chest.open");
            Y = requestSound("entity.chicken.ambient");
            Z = requestSound("entity.chicken.death");
            aa = requestSound("entity.chicken.egg");
            ab = requestSound("entity.chicken.hurt");
            ac = requestSound("entity.chicken.step");
            ad = requestSound("block.chorus_flower.death");
            ae = requestSound("block.chorus_flower.grow");
            af = requestSound("item.chorus_fruit.teleport");
            ag = requestSound("block.cloth.break");
            ah = requestSound("block.cloth.fall");
            ai = requestSound("block.cloth.hit");
            aj = requestSound("block.cloth.place");
            ak = requestSound("block.cloth.step");
            al = requestSound("block.comparator.click");
            am = requestSound("entity.cow.ambient");
            an = requestSound("entity.cow.death");
            ao = requestSound("entity.cow.hurt");
            ap = requestSound("entity.cow.milk");
            aq = requestSound("entity.cow.step");
            ar = requestSound("entity.creeper.death");
            as = requestSound("entity.creeper.hurt");
            at = requestSound("entity.creeper.primed");
            au = requestSound("block.dispenser.dispense");
            av = requestSound("block.dispenser.fail");
            aw = requestSound("block.dispenser.launch");
            ax = requestSound("entity.donkey.ambient");
            ay = requestSound("entity.donkey.angry");
            az = requestSound("entity.donkey.chest");
            aA = requestSound("entity.donkey.death");
            aB = requestSound("entity.donkey.hurt");
            aC = requestSound("entity.egg.throw");
            aD = requestSound("entity.elder_guardian.ambient");
            aE = requestSound("entity.elder_guardian.ambient_land");
            aF = requestSound("entity.elder_guardian.curse");
            aG = requestSound("entity.elder_guardian.death");
            aH = requestSound("entity.elder_guardian.death_land");
            aI = requestSound("entity.elder_guardian.hurt");
            aJ = requestSound("entity.elder_guardian.hurt_land");
            aK = requestSound("item.elytra.flying");
            aL = requestSound("block.enchantment_table.use");
            aM = requestSound("block.enderchest.close");
            aN = requestSound("block.enderchest.open");
            aO = requestSound("entity.enderdragon.ambient");
            aP = requestSound("entity.enderdragon.death");
            aQ = requestSound("entity.enderdragon_fireball.explode");
            aR = requestSound("entity.enderdragon.flap");
            aS = requestSound("entity.enderdragon.growl");
            aT = requestSound("entity.enderdragon.hurt");
            aU = requestSound("entity.enderdragon.shoot");
            aV = requestSound("entity.endereye.launch");
            aW = requestSound("entity.endermen.ambient");
            aX = requestSound("entity.endermen.death");
            aY = requestSound("entity.endermen.hurt");
            aZ = requestSound("entity.endermen.scream");
            ba = requestSound("entity.endermen.stare");
            bb = requestSound("entity.endermen.teleport");
            bc = requestSound("entity.endermite.ambient");
            bd = requestSound("entity.endermite.death");
            be = requestSound("entity.endermite.hurt");
            bf = requestSound("entity.endermite.step");
            bg = requestSound("entity.enderpearl.throw");
            bh = requestSound("block.end_gateway.spawn");
            bi = requestSound("entity.experience_bottle.throw");
            bj = requestSound("entity.experience_orb.pickup");
            bk = requestSound("entity.experience_orb.touch");
            bl = requestSound("block.fence_gate.close");
            bm = requestSound("block.fence_gate.open");
            bn = requestSound("item.firecharge.use");
            bo = requestSound("entity.firework.blast");
            bp = requestSound("entity.firework.blast_far");
            bq = requestSound("entity.firework.large_blast");
            br = requestSound("entity.firework.large_blast_far");
            bs = requestSound("entity.firework.launch");
            bt = requestSound("entity.firework.shoot");
            bu = requestSound("entity.firework.twinkle");
            bv = requestSound("entity.firework.twinkle_far");
            bw = requestSound("block.fire.ambient");
            bx = requestSound("block.fire.extinguish");
            by = requestSound("item.flintandsteel.use");
            bz = requestSound("block.furnace.fire_crackle");
            bA = requestSound("entity.generic.big_fall");
            bB = requestSound("entity.generic.burn");
            bC = requestSound("entity.generic.death");
            bD = requestSound("entity.generic.drink");
            bE = requestSound("entity.generic.eat");
            bF = requestSound("entity.generic.explode");
            bG = requestSound("entity.generic.extinguish_fire");
            bH = requestSound("entity.generic.hurt");
            bI = requestSound("entity.generic.small_fall");
            bJ = requestSound("entity.generic.splash");
            bK = requestSound("entity.generic.swim");
            bL = requestSound("entity.ghast.ambient");
            bM = requestSound("entity.ghast.death");
            bN = requestSound("entity.ghast.hurt");
            bO = requestSound("entity.ghast.scream");
            bP = requestSound("entity.ghast.shoot");
            bQ = requestSound("entity.ghast.warn");
            bR = requestSound("block.glass.break");
            bS = requestSound("block.glass.fall");
            bT = requestSound("block.glass.hit");
            bU = requestSound("block.glass.place");
            bV = requestSound("block.glass.step");
            bW = requestSound("block.grass.break");
            bX = requestSound("block.grass.fall");
            bY = requestSound("block.grass.hit");
            bZ = requestSound("block.grass.place");
            ca = requestSound("block.grass.step");
            cb = requestSound("block.gravel.break");
            cc = requestSound("block.gravel.fall");
            cd = requestSound("block.gravel.hit");
            ce = requestSound("block.gravel.place");
            cf = requestSound("block.gravel.step");
            cg = requestSound("entity.guardian.ambient");
            ch = requestSound("entity.guardian.ambient_land");
            ci = requestSound("entity.guardian.attack");
            cj = requestSound("entity.guardian.death");
            ck = requestSound("entity.guardian.death_land");
            cl = requestSound("entity.guardian.flop");
            cm = requestSound("entity.guardian.hurt");
            cn = requestSound("entity.guardian.hurt_land");
            co = requestSound("item.hoe.till");
            cp = requestSound("entity.horse.ambient");
            cq = requestSound("entity.horse.angry");
            cr = requestSound("entity.horse.armor");
            cs = requestSound("entity.horse.breathe");
            ct = requestSound("entity.horse.death");
            cu = requestSound("entity.horse.eat");
            cv = requestSound("entity.horse.gallop");
            cw = requestSound("entity.horse.hurt");
            cx = requestSound("entity.horse.jump");
            cy = requestSound("entity.horse.land");
            cz = requestSound("entity.horse.saddle");
            cA = requestSound("entity.horse.step");
            cB = requestSound("entity.horse.step_wood");
            cC = requestSound("entity.hostile.big_fall");
            cD = requestSound("entity.hostile.death");
            cE = requestSound("entity.hostile.hurt");
            cF = requestSound("entity.hostile.small_fall");
            cG = requestSound("entity.hostile.splash");
            cH = requestSound("entity.hostile.swim");
            cI = requestSound("entity.husk.ambient");
            cJ = requestSound("entity.husk.death");
            cK = requestSound("entity.husk.hurt");
            cL = requestSound("entity.husk.step");
            cM = requestSound("entity.irongolem.attack");
            cN = requestSound("entity.irongolem.death");
            cO = requestSound("entity.irongolem.hurt");
            cP = requestSound("entity.irongolem.step");
            cQ = requestSound("block.iron_door.close");
            cR = requestSound("block.iron_door.open");
            cS = requestSound("block.iron_trapdoor.close");
            cT = requestSound("block.iron_trapdoor.open");
            cU = requestSound("entity.itemframe.add_item");
            cV = requestSound("entity.itemframe.break");
            cW = requestSound("entity.itemframe.place");
            cX = requestSound("entity.itemframe.remove_item");
            cY = requestSound("entity.itemframe.rotate_item");
            cZ = requestSound("entity.item.break");
            da = requestSound("entity.item.pickup");
            db = requestSound("block.ladder.break");
            dc = requestSound("block.ladder.fall");
            dd = requestSound("block.ladder.hit");
            de = requestSound("block.ladder.place");
            df = requestSound("block.ladder.step");
            dg = requestSound("block.lava.ambient");
            dh = requestSound("block.lava.extinguish");
            di = requestSound("block.lava.pop");
            dj = requestSound("entity.leashknot.break");
            dk = requestSound("entity.leashknot.place");
            dl = requestSound("block.lever.click");
            dm = requestSound("entity.lightning.impact");
            dn = requestSound("entity.lightning.thunder");
            do = requestSound("entity.lingeringpotion.throw");
            dp = requestSound("entity.magmacube.death");
            dq = requestSound("entity.magmacube.hurt");
            dr = requestSound("entity.magmacube.jump");
            ds = requestSound("entity.magmacube.squish");
            dt = requestSound("block.metal.break");
            du = requestSound("block.metal.fall");
            dv = requestSound("block.metal.hit");
            dw = requestSound("block.metal.place");
            dx = requestSound("block.metal_pressureplate.click_off");
            dy = requestSound("block.metal_pressureplate.click_on");
            dz = requestSound("block.metal.step");
            dA = requestSound("entity.minecart.inside");
            dB = requestSound("entity.minecart.riding");
            dC = requestSound("entity.mooshroom.shear");
            dD = requestSound("entity.mule.ambient");
            dE = requestSound("entity.mule.death");
            dF = requestSound("entity.mule.hurt");
            dG = requestSound("music.creative");
            dH = requestSound("music.credits");
            dI = requestSound("music.dragon");
            dJ = requestSound("music.end");
            dK = requestSound("music.game");
            dL = requestSound("music.menu");
            dM = requestSound("music.nether");
            dN = requestSound("block.note.basedrum");
            dO = requestSound("block.note.bass");
            dP = requestSound("block.note.harp");
            dQ = requestSound("block.note.hat");
            dR = requestSound("block.note.pling");
            dS = requestSound("block.note.snare");
            dT = requestSound("entity.painting.break");
            dU = requestSound("entity.painting.place");
            dV = requestSound("entity.pig.ambient");
            dW = requestSound("entity.pig.death");
            dX = requestSound("entity.pig.hurt");
            dY = requestSound("entity.pig.saddle");
            dZ = requestSound("entity.pig.step");
            ea = requestSound("block.piston.contract");
            eb = requestSound("block.piston.extend");
            ec = requestSound("entity.player.attack.crit");
            ed = requestSound("entity.player.attack.knockback");
            ee = requestSound("entity.player.attack.nodamage");
            ef = requestSound("entity.player.attack.strong");
            eg = requestSound("entity.player.attack.sweep");
            eh = requestSound("entity.player.attack.weak");
            ei = requestSound("entity.player.big_fall");
            ej = requestSound("entity.player.breath");
            ek = requestSound("entity.player.burp");
            el = requestSound("entity.player.death");
            em = requestSound("entity.player.hurt");
            en = requestSound("entity.player.levelup");
            eo = requestSound("entity.player.small_fall");
            ep = requestSound("entity.player.splash");
            eq = requestSound("entity.player.swim");
            er = requestSound("entity.polar_bear.ambient");
            es = requestSound("entity.polar_bear.baby_ambient");
            et = requestSound("entity.polar_bear.death");
            eu = requestSound("entity.polar_bear.hurt");
            ev = requestSound("entity.polar_bear.step");
            ew = requestSound("entity.polar_bear.warning");
            ex = requestSound("block.portal.ambient");
            ey = requestSound("block.portal.travel");
            ez = requestSound("block.portal.trigger");
            eA = requestSound("entity.rabbit.ambient");
            eB = requestSound("entity.rabbit.attack");
            eC = requestSound("entity.rabbit.death");
            eD = requestSound("entity.rabbit.hurt");
            eE = requestSound("entity.rabbit.jump");
            eF = requestSound("record.11");
            eG = requestSound("record.13");
            eH = requestSound("record.blocks");
            eI = requestSound("record.cat");
            eJ = requestSound("record.chirp");
            eK = requestSound("record.far");
            eL = requestSound("record.mall");
            eM = requestSound("record.mellohi");
            eN = requestSound("record.stal");
            eO = requestSound("record.strad");
            eP = requestSound("record.wait");
            eQ = requestSound("record.ward");
            eR = requestSound("block.redstone_torch.burnout");
            eS = requestSound("block.sand.break");
            eT = requestSound("block.sand.fall");
            eU = requestSound("block.sand.hit");
            eV = requestSound("block.sand.place");
            eW = requestSound("block.sand.step");
            eX = requestSound("entity.sheep.ambient");
            eY = requestSound("entity.sheep.death");
            eZ = requestSound("entity.sheep.hurt");
            fa = requestSound("entity.sheep.shear");
            fb = requestSound("entity.sheep.step");
            fc = requestSound("item.shield.block");
            fd = requestSound("item.shield.break");
            fe = requestSound("item.shovel.flatten");
            ff = requestSound("entity.shulker.ambient");
            fg = requestSound("entity.shulker_bullet.hit");
            fh = requestSound("entity.shulker_bullet.hurt");
            fi = requestSound("entity.shulker.close");
            fj = requestSound("entity.shulker.death");
            fk = requestSound("entity.shulker.hurt");
            fl = requestSound("entity.shulker.hurt_closed");
            fm = requestSound("entity.shulker.open");
            fn = requestSound("entity.shulker.shoot");
            fo = requestSound("entity.shulker.teleport");
            fp = requestSound("entity.silverfish.ambient");
            fq = requestSound("entity.silverfish.death");
            fr = requestSound("entity.silverfish.hurt");
            fs = requestSound("entity.silverfish.step");
            ft = requestSound("entity.skeleton.ambient");
            fu = requestSound("entity.skeleton.death");
            fv = requestSound("entity.skeleton_horse.ambient");
            fw = requestSound("entity.skeleton_horse.death");
            fx = requestSound("entity.skeleton_horse.hurt");
            fy = requestSound("entity.skeleton.hurt");
            fz = requestSound("entity.skeleton.shoot");
            fA = requestSound("entity.skeleton.step");
            fB = requestSound("entity.slime.attack");
            fC = requestSound("block.slime.break");
            fD = requestSound("entity.slime.death");
            fE = requestSound("block.slime.fall");
            fF = requestSound("block.slime.hit");
            fG = requestSound("entity.slime.hurt");
            fH = requestSound("entity.slime.jump");
            fI = requestSound("block.slime.place");
            fJ = requestSound("entity.slime.squish");
            fK = requestSound("block.slime.step");
            fL = requestSound("entity.small_magmacube.death");
            fM = requestSound("entity.small_magmacube.hurt");
            fN = requestSound("entity.small_magmacube.squish");
            fO = requestSound("entity.small_slime.death");
            fP = requestSound("entity.small_slime.hurt");
            fQ = requestSound("entity.small_slime.jump");
            fR = requestSound("entity.small_slime.squish");
            fS = requestSound("entity.snowball.throw");
            fT = requestSound("entity.snowman.ambient");
            fU = requestSound("entity.snowman.death");
            fV = requestSound("entity.snowman.hurt");
            fW = requestSound("entity.snowman.shoot");
            fX = requestSound("block.snow.break");
            fY = requestSound("block.snow.fall");
            fZ = requestSound("block.snow.hit");
            ga = requestSound("block.snow.place");
            gb = requestSound("block.snow.step");
            gc = requestSound("entity.spider.ambient");
            gd = requestSound("entity.spider.death");
            ge = requestSound("entity.spider.hurt");
            gf = requestSound("entity.spider.step");
            gg = requestSound("entity.splash_potion.break");
            gh = requestSound("entity.splash_potion.throw");
            gi = requestSound("entity.squid.ambient");
            gj = requestSound("entity.squid.death");
            gk = requestSound("entity.squid.hurt");
            gl = requestSound("block.stone.break");
            gm = requestSound("block.stone_button.click_off");
            gn = requestSound("block.stone_button.click_on");
            go = requestSound("block.stone.fall");
            gp = requestSound("block.stone.hit");
            gq = requestSound("block.stone.place");
            gr = requestSound("block.stone_pressureplate.click_off");
            gs = requestSound("block.stone_pressureplate.click_on");
            gt = requestSound("block.stone.step");
            gu = requestSound("entity.stray.ambient");
            gv = requestSound("entity.stray.death");
            gw = requestSound("entity.stray.hurt");
            gx = requestSound("entity.stray.step");
            gy = requestSound("enchant.thorns.hit");
            gz = requestSound("entity.tnt.primed");
            gA = requestSound("block.tripwire.attach");
            gB = requestSound("block.tripwire.click_off");
            gC = requestSound("block.tripwire.click_on");
            gD = requestSound("block.tripwire.detach");
            gE = requestSound("ui.button.click");
            gF = requestSound("entity.villager.ambient");
            gG = requestSound("entity.villager.death");
            gH = requestSound("entity.villager.hurt");
            gI = requestSound("entity.villager.no");
            gJ = requestSound("entity.villager.trading");
            gK = requestSound("entity.villager.yes");
            gL = requestSound("block.waterlily.place");
            gM = requestSound("block.water.ambient");
            gN = requestSound("weather.rain");
            gO = requestSound("weather.rain.above");
            gP = requestSound("entity.witch.ambient");
            gQ = requestSound("entity.witch.death");
            gR = requestSound("entity.witch.drink");
            gS = requestSound("entity.witch.hurt");
            gT = requestSound("entity.witch.throw");
            gU = requestSound("entity.wither.ambient");
            gV = requestSound("entity.wither.break_block");
            gW = requestSound("entity.wither.death");
            gX = requestSound("entity.wither.hurt");
            gY = requestSound("entity.wither.shoot");
            gZ = requestSound("entity.wither.spawn");
            ha = requestSound("entity.wither_skeleton.ambient");
            hb = requestSound("entity.wither_skeleton.death");
            hc = requestSound("entity.wither_skeleton.hurt");
            hd = requestSound("entity.wither_skeleton.step");
            he = requestSound("entity.wolf.ambient");
            hf = requestSound("entity.wolf.death");
            hg = requestSound("entity.wolf.growl");
            hh = requestSound("entity.wolf.howl");
            hi = requestSound("entity.wolf.hurt");
            hj = requestSound("entity.wolf.pant");
            hk = requestSound("entity.wolf.shake");
            hl = requestSound("entity.wolf.step");
            hm = requestSound("entity.wolf.whine");
            hn = requestSound("block.wooden_door.close");
            ho = requestSound("block.wooden_door.open");
            hp = requestSound("block.wooden_trapdoor.close");
            hq = requestSound("block.wooden_trapdoor.open");
            hr = requestSound("block.wood.break");
            hs = requestSound("block.wood_button.click_off");
            ht = requestSound("block.wood_button.click_on");
            hu = requestSound("block.wood.fall");
            hv = requestSound("block.wood.hit");
            hw = requestSound("block.wood.place");
            hx = requestSound("block.wood_pressureplate.click_off");
            hy = requestSound("block.wood_pressureplate.click_on");
            hz = requestSound("block.wood.step");
            hA = requestSound("entity.zombie.ambient");
            hB = requestSound("entity.zombie.attack_door_wood");
            hC = requestSound("entity.zombie.attack_iron_door");
            hD = requestSound("entity.zombie.break_door_wood");
            hE = requestSound("entity.zombie.death");
            hF = requestSound("entity.zombie_horse.ambient");
            hG = requestSound("entity.zombie_horse.death");
            hH = requestSound("entity.zombie_horse.hurt");
            hI = requestSound("entity.zombie.hurt");
            hJ = requestSound("entity.zombie.infect");
            hK = requestSound("entity.zombie_pig.ambient");
            hL = requestSound("entity.zombie_pig.angry");
            hM = requestSound("entity.zombie_pig.death");
            hN = requestSound("entity.zombie_pig.hurt");
            hO = requestSound("entity.zombie.step");
            hP = requestSound("entity.zombie_villager.ambient");
            hQ = requestSound("entity.zombie_villager.converted");
            hR = requestSound("entity.zombie_villager.cure");
            hS = requestSound("entity.zombie_villager.death");
            hT = requestSound("entity.zombie_villager.hurt");
            hU = requestSound("entity.zombie_villager.step");
        }
    }
}
